title: The Saket Upadhyay Blog
email: <firstname><at>virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  Computer Science Ph.D. Student at University of Virginia.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://saketatuva.me/" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: 'G-3EPTCRQJWC' # Substitute this with your own GA key
twitter_username: saketofcyber
github_username:  Saket-Upadhyay
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
collections_dir: _collections

collections:
  columns:
    output: true
  mast:
    output: true


# Social media
twitter: saketofcyber
github: Saket-Upadhyay
linkedin: saketupadhyay
facebook: saketofcyber
